import { Router } from "express";
import { xayDungBoPhuThuoc } from "./container.js";
import { xayDungTuyenDuongXacThuc } from "./modules/auth/presentation/auth.routes.js";
import { xayDungTuyenDuongHocPhan } from "./modules/courses/presentation/course.routes.js";
import { xayDungTuyenDuongDeadline } from "./modules/deadlines/presentation/deadline.routes.js";
import { xayDungTuyenDuongTaiLieuSinhVien } from "./modules/documents/presentation/document.routes.js";
import { xayDungTuyenDuongBoFlashcard } from "./modules/flashcards/presentation/flashcard-deck.routes.js";
import { xayDungTuyenDuongFlashcard } from "./modules/flashcards/presentation/flashcard.routes.js";
import { xayDungTuyenDuongDiemSo } from "./modules/grades/presentation/grade.routes.js";
import { xayDungTuyenDuongSucKhoe } from "./modules/health/health.routes.js";
import { xayDungTuyenDuongKanban } from "./modules/kanban/presentation/kanban.routes.js";
import { xayDungTuyenDuongDinhKemGhiChu } from "./modules/notes/presentation/attachment.routes.js";
import { xayDungTuyenDuongGhiChu } from "./modules/notes/presentation/note.routes.js";
import { xayDungTuyenDuongBaoCaoTaiLieu } from "./modules/report-document/presentation/report-document.routes.js";
import { xayDungTuyenDuongLichHoc } from "./modules/schedules/presentation/schedule.routes.js";
import { xayDungTuyenDuongTruongHoc } from "./modules/schools/presentation/school.routes.js";
import { xayDungTuyenDuongNhomHocTap } from "./modules/study-groups/presentation/study-group.routes.js";
import { xayDungTuyenDuongThongBaoHeThong } from "./modules/notifications/presentation/system-notification.routes.js";
import { xayDungTuyenDuongThongBaoNguoiDung } from "./modules/notifications/presentation/user-notification.routes.js";
import { xayDungTuyenDuongQuanTriHeThong } from "./modules/system-admin/presentation/system-admin.routes.js";
import { xayDungTuyenDuongNguoiDungQuanTri } from "./modules/users/presentation/admin-user.routes.js";
import { xayDungTuyenDuongNguoiDung } from "./modules/users/presentation/user.routes.js";

export const xayDungTuyenDuong = () => {
  const router = Router();
  const boPhuThuoc = xayDungBoPhuThuoc();

  router.use("/health", xayDungTuyenDuongSucKhoe(boPhuThuoc));
  router.use("/auth", xayDungTuyenDuongXacThuc(boPhuThuoc));
  router.use("/users", xayDungTuyenDuongNguoiDung(boPhuThuoc));
  router.use("/notes", xayDungTuyenDuongGhiChu(boPhuThuoc));
  router.use("/attachments", xayDungTuyenDuongDinhKemGhiChu(boPhuThuoc));
  router.use("/courses", xayDungTuyenDuongHocPhan(boPhuThuoc));
  router.use("/deadlines", xayDungTuyenDuongDeadline(boPhuThuoc));
  router.use("/schedules", xayDungTuyenDuongLichHoc(boPhuThuoc));
  router.use("/diem-so", xayDungTuyenDuongDiemSo(boPhuThuoc));
  router.use("/study-groups", xayDungTuyenDuongNhomHocTap(boPhuThuoc));
  router.use("/notifications", xayDungTuyenDuongThongBaoNguoiDung(boPhuThuoc));
  router.use("/kanban", xayDungTuyenDuongKanban(boPhuThuoc));
  router.use("/flashcard-decks", xayDungTuyenDuongBoFlashcard(boPhuThuoc));
  router.use("/flashcards", xayDungTuyenDuongFlashcard(boPhuThuoc));
  router.use("/student/documents", xayDungTuyenDuongTaiLieuSinhVien(boPhuThuoc));
  router.use("/admin/users", xayDungTuyenDuongNguoiDungQuanTri(boPhuThuoc));
  router.use("/admin/schools", xayDungTuyenDuongTruongHoc(boPhuThuoc));
  router.use("/admin/reports", xayDungTuyenDuongBaoCaoTaiLieu(boPhuThuoc));
  router.use("/admin/system-notifications", xayDungTuyenDuongThongBaoHeThong(boPhuThuoc));
  router.use("/admin", xayDungTuyenDuongQuanTriHeThong(boPhuThuoc));

  return router;
};
